package com.example.quizofgot.activity.activity.util;

public class PerguntasERespostas {
    public String[][] casaStark = {
            {"Qual o lema da casa Stark?", "Qual o Brasão da Casa Stark?", "Arma Ancestral que pertence a Casa Stark", "Em qual Região de Westeros fica a Casa Stark?", "Qual o nome da Capital da Casa Stark?", "\"Winterfell é a nossa casa. É nossa, de Arya, de Bran e de Rickon. Onde quer que estejam, pertence à nossa família. Nós temos que lutar por isso.\" ― quem disse isso?", "Quem é a filha mais velha de Catelyn e Eddard Stark?", "Onde Arya foi treinar para se tornar um Homem sem Rosto?", "Quem é a filha mais nova de Lady Catelyn e Lorde Eddard Stark?", "\"Apenas existe um deus; e seu nome é Morte. E apenas tem uma coisa para se dizer para a Morte; 'Hoje não'.\" -Syrio Forel. Para quem foi dito isso?", "Eddard Stark foi conhecido...", "Qual o verdadeiro nome de Ned Stark?", "Qual o nome da única filha do Lorde Rickard Stark?", "Qual o nome do(a) lobo(a) da Arya Stark?", "Quem era Vento Cinzento?", "Qual o nome do(a) lobo(a) da Sansa Stark?"},
            {"\"O inverno está chegando\"", "Um lobo gigante cinza sobre um campo branco", "Gelo", "Norte", "Winterfell", "Sansa Stark", "Sansa Stark", "Casa do Preto e do Branco em Braavos", "Arya Stark", "Arya Stark", "pelo seu senso de honra e justiça", "Eddard Stark", "Lyanna Stark", "Nymeria", "O lobo gigante de Robb Stark", "Lady"},
            {"\"Aqui Nós Resistimos\"", "Cinco setas prateadas em campo marrom", "Irmã Negra", "Dorne", "Dorne", "Melisandra Stark", "Arya Stark", "Dorne", "Rhaena Stark", "Rhaena Stark", "como Ned, o Conquistador", "Brandon Stark", "Sansa Stark", "Lady", "Primo de Robb Stark", "Nymeria"},
            {"\"Nossas lâminas são afiadas\"", "Um leão dourado em um campo carmesim", "Rugido Brilhante", "As Terras da Tempestade", "Lançassolar", "Arya Stark", "Rhaena Stark", "Lançassolar", "Visenya Stark", "Visenya Stark", "como \"O Rei Mendigo\"", "Jon Snow", "Arya Stark", "Vento Cinzento", "Irmão de Robb Stark", "Vento Cinzento"},
            {"\"Nós Não Semeamos\"", "Um veado preto coroado em um campo dourado", "Fazedora de Órfãos", "Terras Ocidentais", "Terras da Coroa", "Tyanna Stark", "Visenya Stark", "Terras da Coroa", "Viserys Stark", "Viserys Stark", "como \"O Cavaleiro da Cebola\"", "Viserys Stark", "Tyanna Stark", "Fantasma", "Tio de Robb Stark", "Fantasma"},
            {"\"Família, Dever, Honra\"", "Um sol vermelho perfurado por uma lança amarela, em campo laranja", "Blackfyre", "Ilhas de Ferro", "Porto Real", "Valaena Stark", "Viserys Stark", "Porto Real", "Tyanna Stark", "Tyanna Stark", "por um senso de justiça duro e inflexível", "Tyanna Stark", "Valaena Stark", "Verão", "Tia de Robb Stark", "Verão"},
            {"\"Tão Alto Como a Honra\"", "Um homem esfolado vermelho de cabeça para baixo em uma cruz sautor branca, sobre fundo preto", "Senhora Desespero", "Para Lá da Muralha", "Campina", "Velaryon Stark", "Tyanna Stark", "Campina", "Valaena Stark", "Valaena Stark", "por seus muitos títulos", "Valaena Stark", "Velaryon Stark", "Inverno", "O Dragão de Robb Stark", "Inverno"},
            {"\"Ouça-me Rugir\"", "Uma lula-gigante dourada em campo negro", "Cumpridora de Promessas", "Vale de Arryn", "Jardim de Cima", "Ceryse Stark", "Valaena Stark", "Jardim de Cima", "Velaryon Stark", "Velaryon Stark", "como \"Bronze Yohn\"", "Velaryon Stark", "Ceryse Stark", "Shell", "O cachorro de Robb Stark", "Shell"},
            {"\"Nossa é a Fúria\"", "Um dragão vermelho de três cabeças sobre fundo negro", "Alvorada", "Terras Fluviais", "Terras Fluviais", "Vhagar Stark", "Velaryon Stark", "Terras Fluviais", "Ceryse Stark", "Ceryse Stark", "por sobreviver a muitas de suas esposas", "Ceryse Stark", "Vhagar Stark", "Cão Felpudo", "O lobo gigante de Arya Stark", "Cão Felpudo"},
            {"\"Crescendo Forte\"", "Uma rosa dourada em fundo verde", "Veneno do Coração", "Campina", "Correrrio", "Balerion Stark", "Ceryse Stark", "Correrrio", "Vhagar Stark", "Vhagar Stark", "como Black Lorren", "Vhagar Stark", "Balerion Stark", "Felpudo", "O lobo gigante de Sansa Stark", "Felpudo"},
            {"\"Primeiros em Batalha\"", "Um dragão negro de três cabeças em um fundo vermelho", "Felpudo", "Terras da Coroa", "Terras da Tempestade", "Essas Stark", "Vhagar Stark", "Terras da Tempestade", "Balerion Stark", "Balerion Stark", "por sua natureza incrivelmente cruel", "Balerion Stark", "Essas Stark", "Rickon", "O lobo gigante de Jon Snow", "Rickon"},
            {"\"Insubmissos, Não Curvados, Não Quebrados\"", "Uma truta prateada saltando em um fundo vermelho e azul", "Rickon", "Essos", "Ponta Tempestade", "Jona Snow", "Balerion Stark", "Ponta Tempestade", "Essos Stark", "Essos Stark", "como o Víbora Vermelha", "Essos Stark", "Jona Snow", "Drogon", "O lobo gigante de Bran Stark", "Drogon"},
            {"\"Um Lannister sempre paga suas dividas\"", "Um falção branco voando e uma lua crescente em fundo azul escuro", "Drogon", "Westeros", "Fé dos Sete", "Septuário Stark", "Essos Stark", "Fé dos Sete", "Jon Snow", "Jon Snow", "como \"Barristan, o ousado\"", "Jon Snow", "Septuário Stark", "Rhaegal", "O lagarto de Bran Stark", "Rhaegal"},
            {"\"Valar Morghulis\"", "Um sol branco sob uma faixa branca vincada, sobre um campo laranja", "Rhaegal", "Sothoryos", "Terras Ocidentais", "Rhaella Stark", "Jon Snow", "Terras Ocidentais", "Septuário Stark", "Septuário Stark", "como \"O Peixe Negro\"", "Septuário Stark", "Rhaella Stark", "Viserion", "O lagarto de Robb Stark", "Viserion"},
            {"\"Valar Dohaeris\"", "Um sabiá negro em um campo amarelo", "Viserion", "Ulthos", "Rochedo Casterly", "Robert Stark", "Septuário Stark", "Rochedo Casterly", "Rhaella Stark", "Rhaella Stark", "como o Casamento Vermelho", "Rhaella Stark", "Robert Stark", "Arrax", "O lagarto de Arya Stark", "Arrax"},
            {"\"Hoje não\"", "Cabeça do Titã de Bravos em um campo verde", "Arrax", "Mar Estreito", "Dádiva", "Catelyn Stark", "Rhaella Stark", "Dádiva", "Robert Stark", "Robert Stark", "como o \"Cavaleiro das Flores\"", "Robert Stark", "Catelyn Stark", "Balerion", "O lagarto de Sansa Stark", "Balerion"},
            {"\"Celas negras\"", "Um machado de batalha negro em campo branco", "Balerion", "Cidades Livres", "Castelo Negro", "Marta Stark", "Robert Stark", "Castelo Negro", "Catelyn Stark", "Catelyn Stark", "como o Senhor de Blackhaven", "Bran Stark", "Marta Stark", "Canibal", "O lagarto de Jon Snow", "Canibal"},
            {"\"Eles podem tirar nossas vidas, mas nunca poderão tirar nossa liberdade\"", "Três cachorros negros em um campo amarelo", "Canibal", "Baía dos Escravos", "Ninho da águia", "Joana Stark", "Catelyn Stark", "Ninho da águia", "Bran Stark", "Bran Stark", "como O Lorde do Mindinho", "Robbo Stark", "Joana Stark", "Dreamfyre", "O cachorro de Arya Stark", "Dreamfyre"},
            {"\"É nosso juízo que faz de nós um homem\"", "Seis flores amarelas sobre campo azul", "Dreamfyre", "Qarth", "Vale de Arryn", "Maria Stark", "Bran Stark", "Vale de Arryn", "Robbo Stark", "Robbo Stark", "como o Senhor dos Ossos", "Sansa Stark", "Maria Stark", "Grey Ghost", "O cachorro de Sansa Stark", "Grey Ghost"},
            {"\"Todos os homens morrem, mas nem todos os homens vivem\"", "Um corvo negro voando segurando um coração", "Grey Ghost", "Terras da Sombra", "Pyke", "Judite Stark", "Robbo Stark", "Pyke", "Sansa Stark", "Sansa Stark", "por todos como \"Edd Doloroso\"", "Rhaena Stark", "Judite Stark", "Ghost", "O cachorro de Bran Stark", "Ghost"}
    };

    public String[][] casaTargaryen = {
            {"Como o pai de Daenerys era infamemente chamado?", "Qual destes NÃ0 é um apelido de Daenerys?", "Qual era o nome da mãe de Daenerys?", "O lar ancestral da Casa Targaryen é chamado de...", "Como se chamava o último irmão sobrevivente de Daenerys?", "Quantos Aegons Targaryen teve em Game of Thrones?", "Qual o nome dos 2 Irmãos de Daenerys Targaryen?", "Qual a origem da casa Targaryen?", "Traços típicos de um Targaryen é...", "O filho mais velho do Rei Aerys II é ...", "Príncipe Rhaegar Targaryen morreu durante ...", "Nome do pai da Daenery", "Primeiro Rei Targaryen", "Aegon Targaryen foi conhecido...", "Nome dos Três dragões de Aegon Targaryen", "Qual o nome do dragão que Rhaenys Targaryen montava?"},
            {"O rei louco", "Senhora dos Seis Reinos", "Rhaella", "Pedra do Dragão", "Viserys", "12", "Rhaeger e Viserys", "Cidade Franca de Valíria", "Cabelos claros e olhos púrpuras.", "Rhaegar Targaryen", "Rebelião de Robert", "Aerys II", "Aegon Targaryen", "como Aegon, o Conquistador", "Vhagar, Meraxes, e Balerion", "Meraxes"},
            {"a Montanha", "Daenerys da Casa Targaryen", "Rhaena", "Porto Real", "Rhaena", "1", "Viserys e Tyanna", "Essos", "Bocas grandes e cabelos claros", "Daenerys Targaryen", "O ataque aos Lannister", "Rhaena", "Rhaena", "pelo seu senso de honra e justiça", "Aelix Targaryen, Baelon Targaryen e Daemion Targaryen", "Rhaena"},
            {"O Assasino de Reis", "Daenerys Nascida na Tormenta", "Visenya", "Terra das Tempestades", "Visenya", "2", "Hightower e Balerion", "Windwyrm", "Cabelos claros e olhos vermelhos", "Visenya", "A reunião em Porto Real", "Visenya", "Visenya", "como \"O Rei Mendigo\"", "Visenya, Viserys e Tyanna", "Visenya"},
            {"a aranha", "Dany", "Viserys", "Casa do Preto e Branco", "Visery", "3", "Meraxes e Viserys", "Septuário", "Bocas grandes e cabelos azul", "Viserys", "Batalha dos Bastardos", "Viserys", "Viserys", "como \"O Cavaleiro da Cebola\"", "Valaena, Ceryse Hightower e Balerion", "Viserys"},
            {"Mãe de Dragões", "A Não-Queimada", "Tyanna", "Drone", "Tyanna", "4", "Windwyrm e Septuário", "Braavos", "Olhos puxados", "Tyanna", "A Estrada do Rei", "Tyanna", "Tyanna", "por um senso de justiça duro e inflexível", "Meraxes, Viserys e a aranha", "Tyanna"},
            {"Nascida da Tormenta", "Mhysa", "Valaena", "Sunspear", "Valaena", "5", "Tyanna e Vhagar", "Sunspear", "cabelos ruivos", "Valaena", "O Lobo e o Leão", "Valaena", "Valaena", "por seus muitos títulos", "Essos, Windwyrm e Septuário", "Valaena"},
            {"Khaleesi", "A Rainha no Outro Lado do Mar", "Velaryon", "Ninho da águia", "Velaryon", "6", "Rhaena e Balerion", "Ninho da águia", "Cabelos Amarelados", "Velaryon", "O Norte Se Lembra", "Velaryon", "Velaryon", "como \"Bronze Yohn\"", "Tyanna, Velaryon e Vhagar", "Velaryon"},
            {"Valaena", "A Rainha Prateada", "Ceryse Hightower", "Rochedo Casterly", "Ceryse Hightower", "7", "Velaryon e Septuário", "Rochedo Casterly", "Cabelos da cor do ceu", "Ceryse Hightower", "O Jardim dos Ossos", "Ceryse Hightower", "Ceryse Hightower", "por sobreviver a muitas de suas esposas", "Meraxes, Rhaena e Balerion", "Ceryse Hightower"},
            {"Dany", "A Rainha Dragão", "Vhagar", "Porto Real", "Vhagar", "8", "Visery e Aerys II", "Porto Real", "Boca pequena", "Vhagar", "O Fantasma de Harrenhal", "Vhagar", "Vhagar", "como Black Lorren", "Velaryon, Balerion e Septuário", "Vhagar"},
            {"A Não-Queimada", "A Princesa Que Foi Prometida", "Meraxes", "Ilhas de Ferro", "a aranha", "9", "Viseryr e Viserys", "Ilhas de Ferro", "Nariz grande", "a aranha", "Batalha da água Negra", "a aranha", "a aranha", "por sua natureza incrivelmente cruel", "Rhaella, Visery e Aerys II", "a aranha"},
            {"Mhysa", "A Rainha no Outro Lado do Mar", "Balerion", "Meereen", "Balerion", "10", "Rhaella e Rhaeger", "Meereen", "Pescoço fino", "Balerion", "Valar Morghulis", "Balerion", "Balerion", "como o Víbora Vermelha", "Visery, Rhaeger e Viserys", "Balerion"},
            {"A Rainha no Outro Lado do Mar", "A Primeira do Seu Nome", "Meraxes", "Nova Ghis", "Essos", "11", "O rei louco e Aerys II", "Nova Ghis", "Pernas longas", "Essos", "Valar Dohaeris", "Essos", "Essos", "como \"Barristan, o ousado\"", "Rhaella, Rhaeger e Viserys", "Essos"},
            {"Essos", "Mãe de Dragões", "Rhaena", "Nova Ibbish", "Windwyrm", "13", "Robert e Meraxes", "Nova Ibbish", "Cabelos prastas e olhos verdes", "Windwyrm", "Beijado Pelo Fogo", "Windwyrm", "Windwyrm", "como \"O Peixe Negro\"", "O rei louco, Rhaella e Aerys II", "Windwyrm"},
            {"Windwyrm", "Daenerys Nascida na Tormenta", "Visenya", "Pentos", "Septuário", "14", "Balerion e Robert", "Pentos", "Nariz pequeno", "Septuário", "A Caminhada da Punição", "Septuário", "Septuário", "como o Casamento Vermelho", "Robert, Aerys II e Meraxes", "Septuário"},
            {"Septuário", "Dany", "Viserys", "Casco", "Rhaella", "15", "Robert e Valaena", "Casco", "Pernas gordas", "Rhaella", "Duas Espadas", "Rhaella", "Rhaella", "como o \"Cavaleiro das Flores\"", "Balerion, a aranha e montanha", "Rhaella"},
            {"Braavos", "A Não-Queimada", "Tyanna", "Cidade do Comerciante", "Robert", "16", "Balerion e Septuário", "Cidade do Comerciante", "Olhos como de peixe", "Robert", "A Montanha e a Víbora", "Robert", "Robert", "como o Senhor de Blackhaven", "Mãe de Dragões, Khaleesi e Valaena", "Robert"},
            {"Sunspear", "Mhysa", "Valaena", "Porto Vermelho", "Rebelião de Robert", "17", "A aranha e montanha", "Porto Vermelho", "Pernas asperas", "Rebelião de Robert", "Septuário", "Rebelião de Robert", "Rebelião de Robert", "como O Lorde do Mindinho", "Hightower, Balerion e Septuário", "Rebelião de Robert"},
            {"Ninho da águia", "A Rainha no Outro Lado do Mar", "Velaryon", "Qohor", "Rebelião de Robert", "18", "Mãe de Dragões e Khaleesi", "Qohor", "Cabelos escuros", "Rebelião de Robert", "Rhaella", "Rebelião de Robert", "Rebelião de Robert", "como o Senhor dos Ossos", "Ceryse, Essos e Windwyrm", "Rebelião de Robert"},
            {"Tyanna", "A Rainha Prateada", "Ceryse Hightower", "Qarth", "Kalisse", "19", "Essos e Windwyrm", "Qarth", "olhos castanhos", "Kalisse", "Robert", "Kalisse", "Kalisse", "por todos como \"Edd Doloroso\"", "Balerion, a aranha e montanha", "Kalisse"},
    };

    public String[][] casaLannister = {
            {"Qual o nome do veneno que matou o rei Joffrey?", "Qual o lema da casa Lannister?", "Qual o nome da Capital da Lannister?", "Qual o Brasão da Casa Lannister?", "Quem é o(a) fundador(a) da Casa Lannister?", "Em qual Região de Westeros fica a Casa Lannister?", "Arma Ancestral que pertence a Casa Lannister", "A Casa Lannister é a primeira casa de que região?", "Qual a principal forma Militar da Casa Lannister?", "Como o Jaime Lannister era conhecido?", "Quando Jaime Lannister nasceu?", "Quem era conhecido como Mão Dourada?", "Quem era conhecido com O Velho Leão?", "Joanna Lannister morreu como?", "Joanna Lannister e Tywin Lannister eram...", "\"Eu sou culpado de um crime muito mais monstruoso: Eu sou culpado de ser um anão!\" quem falou isso?"},
            {"Estrangulador", "\"Ouça-me Rugir\"", "Rochedo Casterly", "Um leão dourado em um campo carmesim", "Lann, o Esperto", "Terras Ocidentais", "Rugido Brilhante", "Terras Ocidentais", "Aprox. 20 000 homens", "Regicida", "266 d.C.", "Jaime Lannister", "Tywin Lannister", "Dando á luz a Tyrion Lannister", "Primos", "Tyrion Lannister"},
            {"Demolidor", "\"Aqui Nós Resistimos\"", "Ponta Tempestade", "Cinco setas prateadas em campo marrom", "Orys Baratheon", "As Terras da Tempestade", "Gelo", "As Terras da Tempestade", "Companhia Dourada", "a Montanha", "200 d.C.", "Arya Lannister", "Arya Lannister", "Envenenada", "Irmãos", "Arya Lannister"},
            {"Assassino", "\"Nossas lâminas são afiadas\"", "Lançassolar", "Um lobo gigante cinza sobre um campo branco", "Desconhecido", "Dorne", "Irmã Negra", "Dorne", "Frota de Ferro", "O rei louco", "357 d.C.", "Rhaena Lannister", "Rhaena Lannister", "Andando de cavalo", "Tio e sobrinha", "Rhaena Lannister"},
            {"Sufocador", "\"Nós Não Semeamos\"", "Forte do Pavor", "Um veado preto coroado em um campo dourado", "Os Primeiros Homens", "Ilhas de Ferro", "Grey Ghost", "Ilhas de Ferro", "Imaculados", "a aranha", "753 d.C.", "Visenya Lannister", "Visenya Lannister", "Esfaqueada", "Tia e sobrinho", "Visenya Lannister"},
            {"Hemlock", "\"Família, Dever, Honra\"", "Winterfell", "Um sol vermelho perfurado por uma lança amarela, em campo laranja", "Rei Cinzento", "Norte", "Fazedora de Órfãos", "Norte", "Dothraki", "Mãe de Dragões", "159 d.C.", "Viserys Lannister", "Viserys Lannister", "Na guerra", "Avô e neta", "Viserys Lannister"},
            {"Aconite", "\"Tão Alto Como a Honra\"", "Dorne", "Um homem esfolado vermelho de cabeça para baixo em uma cruz sautor branca, sobre fundo preto", "Artys Arryn", "Para Lá da Muralha", "Blackfyre", "Para Lá da Muralha", "AK-22", "Nascida da Tormenta", "258 d.C.", "Tyanna Lannister", "Tyanna Lannister", "Por um dragão", "Avó e neto", "Tyanna Lannister"},
            {"Belladonna", "\"O inverno está chegando\"", "Vale de Arryn", "Uma lula-gigante dourada em campo negro", "Daemon I Blackfyre", "Vale de Arryn", "Senhora Desespero", "Vale de Arryn", "Dragões", "Khaleesi", "987 d.C.", "Valaena Lannister", "Valaena Lannister", "Por dois dragões", "Mãe e filho", "Valaena Lannister"},
            {"Dimetil mercúrio", "\"Nossa é a Fúria\"", "Terras da Coroa", "Um dragão vermelho de três cabeças sobre fundo negro", "Baelish", "Terras Fluviais", "Cumpridora de Promessas", "Terras Fluviais", "Benelli MR1", "Valaena", "789 d.C.", "Velaryon Lannister", "Velaryon Lannister", "Com flechas no peito", "Pai e filha", "Velaryon Lannister"},
            {"Tetrodotoxina", "\"Crescendo Forte\"", "Porto Real", "Uma rosa dourada em fundo verde", "Clegane", "Campina", "Alvorada", "Campina", "General Liu rifle", "Dany", "321 d.C.", "Ceryse Lannister", "Ceryse Lannister", "Esfolado", "Tio-avô e sobrinha", "Ceryse Lannister"},
            {"Polônio", "\"Primeiros em Batalha\"", "Campina", "Um dragão negro de três cabeças em um fundo vermelho", "Bran, o Construtor", "Terras da Coroa", "Veneno do Coração", "Terras da Coroa", "Remington Model 742", "A Não-Queimada", "123 d.C.", "Vhagar Stark", "Vhagar Stark", "Com um tiro de canhão", "Tia-avó e sobrinho", "Vhagar Stark"},
            {"Mercúrio", "\"Insubmissos, Não Curvados, Não Quebrados\"", "Jardim de Cima", "Uma truta prateada saltando em um fundo vermelho e azul", "Emmon Frey", "Essos", "Felpudo", "Essos", "Volkssturmgewehr", "Mhysa", "452 d.C.", "Balerion Lannister", "Balerion Lannister", "Atropelado por uma carroça", "Irmãos", "Balerion Lannister"},
            {"Cianeto", "\"Um Lannister sempre paga suas dívidas\"", "Terras Fluviais", "Um falcão branco voando e uma lua crescente em fundo azul escuro", "Daario Naharis", "Westeros", "Rickon", "Westeros", "Jon Snow", "A Rainha no Outro Lado do Mar", "2000 d.C.", "Essos Lannister", "Essos Lannister", "Por homens sem rosto", "Tio e sobrinha", "Essos Lannister"},
            {"Toxina botulínica", "\"Valar Morghulis\"", "Correrrio", "Um sol branco sob uma faixa branca vincada, sobre um campo laranja", "Emilia Clarke", "Sothoryos", "Drogon", "Sothoryos", "Pedersen rifle", "Essos", "2015 d.C.", "Jon Snow", "Jon Snow", "Pelos Imaculados", "Tia e sobrinho", "Jon Snow"},
            {"Arsênico", "\"Valar Dohaeris\"", "Ninho da águia", "Um sabiá negro em um campo amarelo", "Luwin", "Ulthos", "Rhaegal", "Ulthos", "M1941 Johnson rifle", "Windwyrm", "2019 d.C.", "Septuário Lannister", "Septuário Lannister", "Pelos Dothraki", "Avô e neta", "Septuário Lannister"},
            {"Acônito", "\"Hoje não\"", "Ponta Tempestade", "Cabeça do Titã de Bravos em um campo verde", "Jaqen H'ghar", "Mar Estreito", "Viserion", "Mar Estreito", "Winchester model 30", "Septuário", "2174 d.C.", "Rhaella Lannister", "Rhaella Lannister", "Malária", "Avó e neto", "Rhaella Lannister"},
            {"Chapéu Cinzento", "\"Celas negras\"", "Pyke", "Um machado de batalha negro em campo branco", "Tywin Lannister", "Cidades Livres", "Arrax", "Cidades Livres", "PTR 91F", "Braavos", "2 d.C.", "Robert Lannister", "Robert Lannister", "Dengue", "Mãe e filho", "Robert Lannister"},
            {"Fogo Myrês", "\"Eles podem tirar nossas vidas, mas nunca poderão tirar nossa liberdade\"", "Terras Ocidentais", "Três cachorros negros em um campo amarelo", "Cersei Lannister", "Baía dos Escravos", "Balerion", "Baía dos Escravos", "L1A1 Self-Loading Rifle", "Sunspear", "21 d.C.", "Catelyn Lannister", "Catelyn Lannister", "Uma faca no peito", "Pai e filha", "Catelyn Lannister"},
            {"Leite de Fogo", "\"É nosso juízo que faz de nós um homem\"", "Castelo Negro", "Seis flores amarelas sobre campo azul", "Tyrion Lannister", "Qarth", "Canibal", "Qarth", "M110 Semi-Automatic Sniper System", "Ninho da águia", "66 d.C.", "Bran Lannister", "Bran Lannister", "Caindo das escadas", "Tio-avô e sobrinha", "Bran Lannister"},
            {"Lágrima de Lys", "\"Todos os homens morrem, mas nem todos os homens vivem\"", "Dádiva", "Um corvo negro voando segurando um coração", "Jaime Lannister", "Terras da Sombra", "Dreamfyre", "Terras da Sombra", "Demro TAC-1", "Tyanna", "255 d.C.", "Robbo Lannister", "Robbo Lannister", "Caindo de um dragão", "Tia-avó e sobrinho", "Robbo Lannister"}
    };

    public String[][] casaGreyjoy = {
            {"Qual o lema da casa Greyjoy?", "Qual o nome da Capital da Casa Greyjoy?", "Qual o Brasão da Casa Greyjoy?", "Quem é o(a) fundador(a) da Casa Greyjoy?", "Em qual Região de Westeros fica a Casa Greyjoy?", "Qual a principal forma Militar da Casa Greyjoy?", "Qual a religião da Casa Greyjoy?", "Qual a oração comum trocada pelos seguidores do Deus Afogado?", "Quem liderou a Rebelião Greyjoy?", "Quando Theon Greyjoy foi levado como refém pela Casa Stark?", "Qual a data da Rebelião Greyjoy?", "Qual o local da Rebelião Greyjoy?", "Quantos filhos Balon Greyjoy perdeu durante a Rebelião Greyjoy?", "Durante a Rebelião Greyjoy quantos ano Theon Grejoy tinha?", "O que Bran Strak disse para Theon Greyjoy antes que o Rei da noite matasse o Theon?", "Qual o nome da personagem Yara Greyjoy nos livros Gelo e Fogo?"},
            {"\"Nós Não Semeamos\"", "Pyke", "Uma lula-gigante dourada em campo negro", "Rei Cinzento", "Ilhas de Ferro", "Frota de Ferro", "Deus Afogado", "\"O que está morto não pode morrer\"", "Balon Greyjoy", "No final da Rebelião Greyjoy", "289 d.C.", "Westeros", "2", "10", "\"Você é um bom homem. Obrigado.\"", "Asha Greyjoy"},
            {"\"Nossas lâminas são afiadas\"", "Winterfell", "Um homem esfolado vermelho de cabeça para baixo em uma cruz sautor branca, sobre fundo preto", "Os Primeiros Homens", "Norte", "Companhia Dourada", "Deus de Muitas Faces", "Pai nosso", "Arya Greyjoy", "na batalha Arena de Daznak", "200 d.C.", "Dorne", "1", "9", "\"O que está morto não pode morrer\"", "Arya Greyjoy"},
            {"\"Insubmissos, Não Curvados, Não Quebrados\"", "Dorne", "Um sol vermelho perfurado por uma lança amarela, em campo laranja", "Desconhecido", "Dorne", "Aprox. 20 000 homens", "Deuses Antigos da Floresta", "\"Apenas existe um deus; e seu nome é Morte. E apenas tem uma coisa para se dizer para a Morte: 'Hoje não'.\"", "Rhaena Greyjoy", "No final da Batalha do Vago", "357 d.C.", "Terras de Sempre Inverno", "3", "8", "\"Irineu\"", "Rhaena Greyjoy"},
            {"\"Aqui Nós Resistimos\"", "Lançassolar", "Um veado preto coroado em um campo dourado", "Orys Baratheon", "As Terras da Tempestade", "Imaculados", "Deus-Rei de Ibben", "\"representa a justiça divina, e julga as almas dos mortos.\"", "Visenya Greyjoy", "Batalha dos Bastardos", "753 d.C.", "Muralha", "4", "7", "\"Olokinho Meu\"", "Visenya Greyjoy"},
            {"\"Todos os homens morrem, mas nem todos os homens vivem\"", "Terras da Coroa", "Um leão dourado em um campo carmesim", "Lann, o Esperto", "Terras Ocidentais", "Dothraki", "Fé dos Sete", "\"representa a misericórdia, a paz, a fertilidade e o nascimento.\"", "Viserys Greyjoy", "Batalha dos Sinos", "159 d.C.", "Esso", "5", "11", "\"Meu amigo bicho\"", "Viserys Greyjoy"},
            {"\"É nosso juízo que faz de nós um homem\"", "Porto Real", "Cinco setas prateadas em campo marrom", "Artys Arryn", "Para Lá da Muralha", "Dragões", "O Pai", "\"representa a misericórdia, a paz, a fertilidade e o nascimento.\"", "Tyanna Greyjoy", "Batalha dos Acampamentos", "258 d.C.", "Mar Estreito", "6", "12", "\"Eu tenho um probleminha\"", "Tyanna Greyjoy"},
            {"\"Família, Dever, Honra\"", "Campina", "Um lobo gigante cinza sobre um campo branco", "Daemon I Blackfyre", "Vale de Arryn", "AK-22", "Deuses Novos", "\"representa pureza, inocência, amor e beleza.\"", "Valaena Greyjoy", "Batalha do Tridente", "987 d.C.", "Mar de Verão", "7", "13", "\"Não vai que o Rei da noite vai te matar\"", "Valaena Greyjoy"},
            {"\"Tão Alto Como a Honra\"", "Jardim de Cima", "Um dragão vermelho de três cabeças sobre fundo negro", "Baelish", "Terras Fluviais", "Dragões", "Deus de Sete Faces", "\"representa a sabedoria e clarividência. Ela é representada carregando uma lanterna.\"", "Velaryon Greyjoy", "Batalha pela Aurora", "789 d.C.", "Ilhas de Verão", "8", "14", "\"Relaxa aqui que a Arya está vindo\"", "Velaryon Greyjoy"},
            {"\"O inverno está chegando\"", "Terras Fluviais", "Uma rosa dourada em fundo verde", "Clegane", "Campina", "Benelli MR1", "A Mãe", "\"representa força e coragem na batalha.\"", "Ceryse Greyjoy", "Batalha de Guardamar", "321 d.C.", "Ilhas de Ferro", "9", "15", "\"Valar Morghulis\"", "Ceryse Greyjoy"},
            {"\"Ouça-me Rugir\"", "Correrrio", "Um dragão negro de três cabeças em um fundo vermelho", "Bran, o Construtor", "Terras da Coroa", "General Liu rifle", "A Donzela", "\"representa a criação e artesanato.\"", "Vhagar Greyjoy", "Batalha de Solarestival", "123 d.C.", "Deus de Muitas Faces", "10", "16", "\"Valar Dohaeris\"", "Vhagar Greyjoy"},
            {"\"Crescendo Forte\"", "Terras da Tempestade", "Uma truta prateada saltando em um fundo vermelho e azul", "Emmon Frey", "Essos", "Remington Model 742", "A Velha", "\"representa a morte e o desconhecido. Raramente oram a ele.\"", "Balerion Greyjoy", "No final da batalha de Vaufreixo", "452 d.C.", "Deuses Antigos da Floresta", "11", "17", "\"Daenarys é louca\"", "Balerion Greyjoy"},
            {"\"Primeiros em Batalha\"", "Ponta Tempestade", "Um falcão branco voando e uma lua crescente em fundo azul escuro", "Daario Naharis", "Westeros", "Volkssturmgewehr", "O Guerreiro", "\"Valar Morghulis\"", "Essos Greyjoy", "No final da Batalha de Valdocaso", "2000 d.C.", "Deus-Rei de Ibben", "12", "18", "\"HODOR\"", "Essos Greyjoy"},
            {"\"Nossa é a Fúria\"", "Fé dos Sete", "Um sol branco sob uma faixa branca vincada, sobre um campo laranja", "Emilia Clarke", "Sothoryos", "Jon Snow", "O Ferreiro", "\"Valar Dohaeris\"", "Jon Snow", "No final da Batalha de Qohor", "2015 d.C.", "Sothoryos", "13", "19", "\"Melhor agora do que queimado depois\"", "Jon Snow"},
            {"\"Um Lannister sempre paga suas dividas\"", "Terras Ocidentais", "Um sabiá negro em um campo amarelo", "Luwin", "Ulthos", "Pedersen rifle", "O Estranho", "\"Tão Alto Como a Honra\"", "Septuário Greyjoy", "No final da Batalha de Cruzaboi", "2019 d.C.", "Ulthos", "14", "20", "\"Vai pega Fogo bixo\"", "Septuário Greyjoy"},
            {"\"Valar Morghulis\"", "Rochedo Casterly", "Cabeça do Titá de Bravos em um campo verde", "Jaqen H'ghar", "Mar Estreito", "M1941 Johnson rifle", "Os Sete", "\"O inverno está chegando\"", "Rhaella Greyjoy", "No final da batalha dos Vaus", "2174 d.C.", "Mar Estreito", "15", "21", "\"Eu não sou o corvo\"", "Rhaella Greyjoy"},
            {"\"Valar Dohaeris\"", "Dádiva", "Um machado de batalha negro em campo branco", "Tywin Lannister", "Cidades Livres", "Winchester model 30", "Os deuses sem rosto", "\"Ouça-me Rugir\"", "Robert Greyjoy", "No final da Batalha da água Negra", "2 d.C.", "Baía dos Escravos", "16", "22", "\"Eu sou o vilão\"", "Robert Greyjoy"},
            {"\"Hoje não\"", "Castelo Negro", "Três cachorros negros em um campo amarelo", "Cersei Lannister", "Baía dos Escravos", "PTR 91F", "Ándalos", "\"Crescendo Forte\"", "Catelyn Greyjoy", "No final da Batalha de Lago Longo", "21 d.C.", "A Mãe", "17", "23", "\"Eu quero ficar com a Daenarys", "Catelyn Greyjoy"},
            {"\"Celas negras\"", "Ninho da águia", "Seis flores amarelas sobre campo azul", "Tyrion Lannister", "Qarth", "L1A1 Self-Loading Rifle", "Represeiro", "\"Hoje não\"", "Bran Greyjoy", "No início da Rebelião Greyjoy", "66 d.C.", "Cidades Livres", "18", "24", "\"Não gosto de dar Spoiler\"", "Bran Greyjoy"},
            {"\"Eles podem tirar nossas vidas, mas nunca poderão tirar nossa liberdade\"", "Vale de Arryn", "Um corvo negro voando segurando um coração", "Jaime Lannister", "Terras da Sombra", "M110 Semi-Automatic Sniper System", "Cristianismo", "\"Celas negras\"", "Yara Greyjoy", "No final da batalha do Bosque dos Murmúrios", "255 d.C.", "Qarth", "19", "25", "\"Eu queria que got passasse na netflix\"", "Yara Greyjoy"}
    };

}
